#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1;36mScenario 2\033[0m  ·  Two skills fire on the same turn\n'
printf '\n'
printf '  Prompt:  "Write a git commit for adding request-id tracing to Flask"\n'
printf '\n'
printf '  "flask"  triggers  \033[1mpython\033[0m  skill  (~550t)\n'
printf '  "commit" triggers  \033[1mgit\033[0m     skill  (~400t)\n'
printf '\n'
printf '  \033[2mwatch:  ↳ skills: python, git  — both injected, one turn\033[0m\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
