#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1;36mScenario 3\033[0m  ·  Casual message — no skills injected\n'
printf '\n'
printf '  Prompt:  "Nice, thanks!"\n'
printf '\n'
printf '  zap detects this is conversational — not a coding task.\n'
printf '  No skills are injected. A minimal ~200-token prompt is used.\n'
printf '\n'
printf '  \033[2mwatch:  no ↳ skills line  — the amber indicator is absent\033[0m\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
