#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1;36mScenario 1\033[0m  ·  Python skill auto-injection\n'
printf '\n'
printf '  Prompt:  "How should I handle database errors in a Flask route?"\n'
printf '\n'
printf '  zap detects \033[1mflask\033[0m keyword + \033[1mpyproject.toml\033[0m in the project\n'
printf '  and injects the Python conventions skill for this turn only.\n'
printf '\n'
printf '  \033[2mwatch:  ↳ skills: python  appears before the response\033[0m\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
