#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1m⚡ zap\033[0m  ·  \033[1mCode Indexing Demo\033[0m\n'
printf '\n'
printf '  tree-sitter  →  SQLite  →  instant symbol lookup\n'
printf '  pallets/flask  ·  83 files  ·  1 577 symbols indexed\n'
printf '\n'
printf '  The LLM \033[1mqueries the index\033[0m — no guessing, no blind directory reads.\n'
printf '  Result: 3–5× fewer tool calls. More tokens for actual reasoning.\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
