#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1;36m4/5\033[0m  ·  /init — Auto-Bootstrap Project Knowledge\n'
printf '\n'
printf '  /init analyses your repo and generates context files:\n'
printf '\n'
printf '    \033[1mZAP.md\033[0m            project overview, build commands, architecture\n'
printf '    \033[1m.zap/understanding.md\033[0m  deep technical map, data flows, patterns\n'
printf '    \033[1m.zap/context.md\033[0m      auto-updated every session\n'
printf '\n'
printf '  \033[2mLoaded on-demand — never pre-loaded into context.\033[0m\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
