#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1;36m1/5\033[0m  ·  Skill-First Context Injection\n'
printf '\n'
printf '  Most agents send the same massive system prompt every turn.\n'
printf '  zap injects skills \033[1monly when they match\033[0m your message.\n'
printf '\n'
printf '  \033[2mPython question → python skill   ·   git question → git skill\033[0m\n'
printf '  \033[2mCasual greeting  → no skill injected at all\033[0m\n'
printf '\n'
printf '  \033[2mWatch for:  ↳ skills: python  (amber highlight in zap output)\033[0m\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
