#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1m⚡ zap\033[0m\n'
printf '\n'
printf '  ✓  Skill-first injection  —  context that earns its place\n'
printf '  ✓  AST code index         —  find_definition in 1 call\n'
printf '  ✓  Casual turn detection  —  greetings cost ~31 tokens\n'
printf '  ✓  /init bootstrapping    —  project knowledge out of the box\n'
printf '  ✓  Hard security boundary —  ask / auto / deny modes\n'
printf '\n'
printf '  \033[1mOne binary. No runtime. MIT licensed.\033[0m\n'
printf '\n'
printf '  \033[2mgithub.com/sgulati/zap\033[0m\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
