#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1m⚡ zap\033[0m  ·  \033[1mContext Viewer  —  full visibility, full control\033[0m\n'
printf '\n'
printf '  Every AI coding tool shows you a context percentage.\n'
printf '  That is all you get — a number, no explanation.\n'
printf '\n'
printf '  \033[1mzap /context\033[0m shows you:\n'
printf '    ▸  every turn and its exact token cost\n'
printf '    ▸  which turns are live vs already stubbed\n'
printf '    ▸  the real content — prompts, tool calls, full results\n'
printf '    ▸  surgical drop of any turn, compact, or clear\n'
printf '\n'
printf '  \033[2mFirst time this exists in any AI coding agent.\033[0m\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
