#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1m⚡ zap\033[0m  ·  /context\n'
printf '\n'
printf '  ✓  See every turn, its exact token cost and %% of context\n'
printf '  ✓  ▓ = live in window   ░ = already stubbed\n'
printf '  ✓  Open detail view — real prompts, tool calls, full results\n'
printf '  ✓  Navigate with j/k — drop any turn with d\n'
printf '  ✓  Compact or clear — always with confirmation\n'
printf '\n'
printf '  \033[1mFull visibility. Full control. No black box.\033[0m\n'
printf '  \033[2mNothing like this exists anywhere else.\033[0m\n'
printf '\n'
printf '  \033[2mgithub.com/zap-coding-agent/zap-coding-agent\033[0m\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
